import { useQuery } from "@tanstack/react-query";
import { type NextPage } from "next";
import { Permanent_Marker } from "next/font/google";
import Head from "next/head";
import Link from "next/link";

type PhotoType = {
  albumId: number;
  id: number;
  title: string;
  url: string;
  thumbnailUrl: string;
};

const permMarker = Permanent_Marker({
  weight: "400",
  subsets: ["latin"],
});

const Home: NextPage = () => {
  const {
    isLoading,
    error,
    data: photos,
  } = useQuery<PhotoType[]>({
    queryKey: ["photoData"],
    queryFn: () =>
      fetch("https://jsonplaceholder.typicode.com/photos?albumId=3").then(
        (res) => res.json()
      ),
  });

  return (
    <>
      <Head>
        <title>Deren Showcase Photo Album</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#0ABAB5] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center px-4 py-16">
          <h1 className="pb-6 text-4xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Deren <span className="text-[#006666]">Photo</span> Album
          </h1>
          <div className="columns-1 space-y-4 sm:columns-2 md:columns-3">
            {photos?.map((photo) => (
              <Link
                key={photo.id}
                className="hover:tilt flex flex-col rounded-sm bg-slate-200 p-2 pb-8 duration-300 ease-in-out hover:-translate-y-3 hover:-rotate-1 hover:shadow-xl hover:shadow-black/40"
                href={photo.url}
                target="_blank"
              >
                <img
                  className="h-full w-full"
                  src={photo.url}
                  alt={photo.thumbnailUrl}
                  // width={150}
                  // height={150}
                />
                <div className={`${permMarker.className} h-10 text-lg`}>
                  {`${photo.id}) ${photo.title}`}
                </div>
              </Link>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
